version: '3'

services:
  client:
    build: .
    environment:
      REACT_APP_PORT: ${REACT_APP_PORT}
    expose:
      - ${REACT_APP_PORT}
    ports: 
      - ${REACT_APP_PORT}:${REACT_APP_PORT}
    volumes:
      - ./src:/srv/app/exploreat_client/src
      - ./public:/srv/app/exploreat_client/public
    command: ["yarn", "dev"]
